# Generated by Django 3.1.1 on 2020-11-13 03:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified on')),
                ('name', models.CharField(help_text='A unique string to name this quota type', max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Detail Explanation for this quota', null=True, verbose_name='Description')),
                ('company', models.ForeignKey(blank=True, help_text='Company who own this quota type', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_qms_quota_set', to='base.user', verbose_name='Created by')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_qms_quota_set', to='base.user', verbose_name='Last Modified by')),
            ],
            options={
                'verbose_name': 'Quota',
            },
        ),
        migrations.CreateModel(
            name='QuotaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified on')),
                ('name', models.CharField(help_text='A unique string to name this quota', max_length=255, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='You can disable a account without deleting it', verbose_name='Active')),
                ('company', models.ForeignKey(blank=True, help_text='Company who own this account', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_qms_quotaaccount_set', to='base.user', verbose_name='Created by')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_qms_quotaaccount_set', to='base.user', verbose_name='Last Modified by')),
            ],
            options={
                'verbose_name': 'Quota Account',
            },
        ),
        migrations.CreateModel(
            name='QuotaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified on')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_qms_quotatransaction_set', to='base.user', verbose_name='Created by')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_trans', to='qms.quotaaccount', verbose_name='From Account')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qms.quota', verbose_name='Quota')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_trans', to='qms.quotaaccount', verbose_name='To Account')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_qms_quotatransaction_set', to='base.user', verbose_name='Last Modified by')),
            ],
            options={
                'verbose_name': 'Quota Transaction',
            },
        ),
        migrations.CreateModel(
            name='QuotaInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Report - Quota Inventory',
                'verbose_name_plural': 'Report - Quota Inventory',
                'db_table': 'quota_inventory',
                'managed': False,
            },
        ),
        migrations.RunSQL(
        """
        CREATE MATERIALIZED VIEW "qms_quotainventory" AS
            WITH account_flow AS (
                SELECT
                    "qms_quotatransaction"."to_account_id" AS "account_id",
                    "qms_quotatransaction"."quota_id",
                    "qms_quotatransaction"."quantity"
                FROM
                    "qms_quotatransaction"
                WHERE
                    NOT ("qms_quotatransaction"."quantity" = 0)
                UNION
                SELECT
                    "qms_quotatransaction"."from_account_id" AS "account_id",
                    "qms_quotatransaction"."quota_id",
                    - "qms_quotatransaction"."quantity"
                FROM
                    "qms_quotatransaction"
                WHERE
                    NOT ("qms_quotatransaction"."quantity" = 0)
                )
            SELECT
                ROW_NUMBER () OVER (
                    ORDER BY "account_id", "quota_id"
                ) as id,
                "account_id",
                "quota_id",
                SUM("quantity") as quantity
            FROM
                account_flow
            GROUP BY "account_id", "quota_id"
            ORDER BY "account_id", "quota_id"
        ;
        CREATE UNIQUE INDEX "quotainventory_account_quota_index" ON "qms_quotainventory" ("account_id", "quota_id")
        ;
        """,
        reverse_sql=
        """
        DROP MATERIALIZED VIEW "qms_quotainventory";
        """
        ),
    ]
